[package]
name = "binary-visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
candle = { version = "0.3.0", package = "candle-core" }
candle-nn = "0.3.0"
macroquad = "0.4.4"
